#!/bin/bash

# gamma correction
# xgamma -rgamma 0.95 -ggamma 0.95 -bgamma 1.1 &

# glava &
sxhkd &
setxkbmap -layout "us,ua,ru" -option "grp:alt_shift_toggle"
numlockx &
dunst &
/usr/lib/polkit-kde-authentication-agent-1 &
picom &
feh --bg-scale ~/.config/Wallpapers/1.jpg
polybar &

google-chrome-stable &
telegram-desktop &
teams-for-linux &

bspc rule -a google-chrome-stable desktop='^1'
bspc rule -a teams-for-linux desktop='^10' follow=off
bspc rule -a TelegramDesktop desktop='^10' follow=off

bspc monitor -d                   

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier  super

bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle   true
